#Task 1 :Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library).

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43], 
                    [91, 88, 64], 
                    [87, 134, 58], 
                    [102, 43, 37], 
                    [69, 96, 70]], dtype='float32')
print(inputs.shape)

(15, 3)


In [3]:
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,test_size=0.4, random_state=58)

In [5]:
reg = LinearRegression().fit(x_train,y_train)
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [6]:
print(reg.intercept_)
print(reg.coef_)

[-3.5643997 -2.0832367]
[[-0.38395885  0.8440443   0.73600304]
 [-0.2854117   0.7942672   0.92232394]]


In [7]:
y_pred = reg.predict(x_test)
print(y_pred,"\n")
print(y_test)

[[ 82.87544  100.868546]
 [ 82.87544  100.868546]
 [ 20.797815  37.084248]
 [ 56.605705  69.95754 ]
 [ 20.797815  37.084248]
 [118.8213   133.01253 ]] 

[[ 81. 101.]
 [ 81. 101.]
 [ 22.  37.]
 [ 56.  70.]
 [ 22.  37.]
 [119. 133.]]


In [8]:
from sklearn import metrics
print('\n Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))


 Mean Squared Error: 0.86454946
