#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.69696562, 0.56265268],
       [0.36620476, 0.09873505],
       [0.37247523, 0.44986804]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([1.61761891, 0.44536691])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 93.04826316  67.47858662]
 [121.10592411  89.12699973]
 [132.92862928  88.71899303]
 [102.23650063  78.72666499]
 [110.93716983  80.23772935]
 [ 93.04826316  67.47858662]
 [121.10592411  89.12699973]
 [132.92862928  88.71899303]
 [102.23650063  78.72666499]
 [110.93716983  80.23772935]
 [ 93.04826316  67.47858662]
 [121.10592411  89.12699973]
 [132.92862928  88.71899303]
 [102.23650063  78.72666499]
 [110.93716983  80.23772935]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(1502.7721800145998, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 1502.7721800145998
 
 Epoch count: 1 
 Loss value: 1158.6134557434298
 
 Epoch count: 2 
 Loss value: 916.9589817833267
 
 Epoch count: 3 
 Loss value: 742.655098354686
 
 Epoch count: 4 
 Loss value: 613.3144504314281
 
 Epoch count: 5 
 Loss value: 514.5847267859054
 
 Epoch count: 6 
 Loss value: 437.1828535911831
 
 Epoch count: 7 
 Loss value: 375.0343789763931
 
 Epoch count: 8 
 Loss value: 324.1049007723999
 
 Epoch count: 9 
 Loss value: 281.66499534141803
 
 Epoch count: 10 
 Loss value: 245.82683569390403
 
 Epoch count: 11 
 Loss value: 215.25120963984725
 
 Epoch count: 12 
 Loss value: 188.96151879599537
 
 Epoch count: 13 
 Loss value: 166.2250371416717
 
 Epoch count: 14 
 Loss value: 146.47653881564116
 
 Epoch count: 15 
 Loss value: 129.26868806719975
 
 Epoch count: 16 
 Loss value: 114.23939621290587
 
 Epoch count: 17 
 Loss value: 101.089990229445
 
 Epoch count: 18 
 Loss value: 89.57031802538584
 
 Epoch count: 19 
 Loss value: 7